feat: don't JSON encode requests with XML mimetype
granodigital/openapi-client pull request #13
Opened 2023-09-20 07:25 UTC by jkumara

Handle requests with XML mimetypes correctly. I did a check on XML mimetype rather than on JSON mimetype to minimize the change of accidentally breaking something😅

2023-09-20 07:44 UTC, villelahdenvuo commented on src/gen/js/service.js.template
Must also change in the ts template?

2023-09-20 07:44 UTC, villelahdenvuo requested changes
Change needed in TS template?

2023-09-25 11:47 UTC, jkumara commented on src/gen/js/service.js.template
Yes, I missed that.

2023-09-25 13:26 UTC, villelahdenvuo commented on src/gen/js/service.ts.template
> +  const fetchOptions = {
indent

2023-09-25 15:43 UTC, villelahdenvuo requested changes

2023-09-25 15:43 UTC, villelahdenvuo commented on src/gen/js/service.ts.template
> +	const body = isXmlRequest ? req.body : JSON.stringify(req.body || undefined);
Not actually used?

2023-09-29 06:32 UTC, jkumara commented on src/gen/js/service.ts.template
> +	const body = isXmlRequest ? req.body : JSON.stringify(req.body || undefined);
Argh, too hasty copy-paste

2023-09-29 08:59 UTC, merged